apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::323789138745:user/github-ci
      username: github-ci
      groups:
        -system:masters